name: Socialite
favicon: null
layout_spectrum: 0.4916178302373737
typography_spectrum: 0.15482124406844378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.08389215311035514
  lightness: 0.7378994182217866
  saturation: 0.3872430492192507
  rhythmicContrast: 0.1974777290597558
purpose: []
